title: A sample site
author: David 
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Blah blah blah this is the description.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
